attachment/attachment/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [path("admin/", admin.site.urls)]

urlpatterns += i18n_patterns(
    path("surveys/", include("surveys.urls")), prefix_default_language=True
)

attachment/surveys/urls.py
# Add urls to the views in surveys app.
#
# Path: attachment-project\attachment\surveys\urls.py
from django.urls import path
from .views import SurveyView, RecordingView


urlpatterns = [
    path("<slug:slug>/", SurveyView.as_view(), name="survey"),
    path("<slug:slug>/recording/", RecordingView.as_view(), name="recording"),
]

attachment/surveys/models.py
import json
from enum import Enum
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _


class LanguageEnum(Enum):
    SPANISH = "es"
    ENGLISH = "en"
    PORTUGUESE = "pt"

    @classmethod
    def choices(cls):
        return [(e.value, _(e.name.capitalize())) for e in cls]


class Survey(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60, unique=True)
    next_survey = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/surveys/{self.slug}/"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.name
        super().save(*args, **kwargs)


class Screen(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name="screens")
    order = models.IntegerField()

    def __str__(self):
        return f"{self.survey.name} - Screen {self.order}"

    class Meta:
        ordering = ["order"]


class SurveyTranslation(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    language = models.CharField(max_length=60, choices=LanguageEnum.choices())
    title = models.CharField(max_length=255)

    class Meta:
        unique_together = [("survey", "language")]


class Question(models.Model):
    TEXT = "text"
    SINGLE_SELECT = "single_select"
    MULTIPLE_SELECT = "multiple_select"
    LIKERT_5 = "likert_5"
    LIKERT_7 = "likert_7"
    NUMBER = "number"
    PROMPT = "prompt"
    RECORDING = "recording"

    QUESTION_TYPES = [
        (TEXT, "Text"),
        (SINGLE_SELECT, "Single Select"),
        (MULTIPLE_SELECT, "Multiple Select"),
        (LIKERT_5, "likert_5"),
        (LIKERT_7, "likert_7"),
        (NUMBER, "number"),
        (PROMPT, "prompt"),
        (RECORDING, "recording"),
    ]
    name = models.CharField(max_length=60)
    survey = models.ManyToManyField(Survey, related_name="questions")
    question_type = models.CharField(max_length=60, choices=QUESTION_TYPES)
    order = models.IntegerField()
    hidden = models.BooleanField(default=False)
    screen = models.ForeignKey(
        Screen,
        on_delete=models.CASCADE,
        related_name="questions",
        null=True,
        blank=True,
    )
    exclusion_value = models.JSONField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["order"]


class QuestionTranslation(models.Model):
    survey_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    language = models.CharField(max_length=60, choices=LanguageEnum.choices())
    question_prompt = models.TextField()
    options = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        unique_together = [("survey_question", "language")]

    def __str__(self):
        return self.question_prompt


class Answer(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    answers = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)

    def set_answers(self, answers):
        self.answers = json.dumps(answers)

    def get_answers(self):
        return json.loads(self.answers)


class Recording(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)
    recording = models.FileField(upload_to="recordings/")
    language = models.CharField(max_length=60, choices=LanguageEnum.choices())
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    class Meta:
        verbose_name = "Record"
        verbose_name_plural = "Records"

    def __str__(self):
        return str(self.recording)

    def get_absolute_url(self):
        return self.recording.url

    def get_recording_name(self):
        return self.recording.name.split("/")[-1]

    def get_recording_size(self):
        return self.recording.size

    def get_recording_type(self):
        return self.recording.content_type

attachment/surveys/views.py
import os
import json
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import Survey, Answer, Recording, Question
from .prolific import get_profilic_params, get_prolific_redirect
import uuid

import logging

logger = logging.getLogger(__name__)


FILE_PATH = os.path.dirname(os.path.abspath(__file__))


class SurveyView(View):
    def get(self, request, slug):
        survey = get_object_or_404(Survey, slug=slug)
        survey_uuid = request.GET.get("uuid", str(uuid.uuid4()))
        prolific_params = get_profilic_params(request.GET)
        # get the screens
        screens = {}
        for screen in survey.screens.all():
            screens[screen.id] = []
            # check the questions in the screen
            for question in screen.questions.all():
                if question.exclusion_value:
                    question.exclusion_value = json.dumps(question.exclusion_value)
                question_class = False
                for translation in question.questiontranslation_set.all():
                    for option in translation.options:
                        if option.get("image"):
                            question.image = option["image"]
                        if len(option["label"]) > 30:
                            question_class = True
                            break
                question.long_text = question_class
                screens.get(screen.id).append(question)
        survey.checked_screens = screens
        return render(
            request,
            f"{FILE_PATH}/templates/survey.html",
            {"survey": survey, "uuid": survey_uuid, **prolific_params},
        )

    def post(self, request, slug):
        survey = Survey.objects.get(slug=slug)
        language = request.POST.get("language")
        # Retrieve the answers for each question from the request
        answers = {}
        audio_uuids = []
        excluded = False
        consent = True
        bad_device = False
        completed = True
        prolific_redirect = ""
        for key, value in request.POST.items():
            if key == "response-uuid":
                answers["response-uuid"] = value
                response_uuid = value
            if key == "excluded":
                excluded = json.loads(value)
                if "consent" in survey.slug:
                    consent = False
            if key.startswith("question_") or key in ["language"]:
                question_id = key.replace("question_", "")
                answers[question_id] = value
            if key.startswith("audio_"):
                audio_id = key.replace("audio_", "")
                if value:
                    if "Blob" in value:
                        bad_device = True
                    answers[audio_id] = value
                    audio_uuids.append(value)
        # check if all questions have been answered, excluding the questions that are prompts and the language
        question_count = Question.objects.filter(
            screen__survey=survey,
            question_type__in=[
                "text",
                "single_select",
                "multiple_select",
                "likert_5",
                "likert_7",
                "number",
                "recording",
            ],
        ).count()
        if len(answers) < question_count:
            completed = False
        extra_params = {}
        if extra_params := get_profilic_params(request.GET):
            answers = {**answers, **extra_params}
            if None not in extra_params.values():
                prolific_redirect = get_prolific_redirect(
                    consent=consent,
                    excluded=excluded,
                    bad_device=bad_device,
                    completed=completed,
                )
        answers = json.dumps(answers)
        answer = Answer(survey=survey, answers=answers)
        answer.save()

        if audio_uuids:
            Recording.objects.filter(uuid__in=audio_uuids).update(answer=answer)
        if survey.next_survey and not excluded and consent and not bad_device:
            redirect_url = f"/{language}{survey.next_survey.get_absolute_url()}"
            # Add uuid as a parameter to the redirect url
            redirect_url += f"?uuid={response_uuid}"
            if extra_params:
                for key, value in extra_params.items():
                    redirect_url += f"&{key}={value}"
            # render the next survey
            return redirect(redirect_url)
        if prolific_redirect:
            return redirect(prolific_redirect)
        return render(request, f"{FILE_PATH}/templates/survey_submit.html")


class RecordingView(View):
    def post(self, request, slug):
        language = request.POST.get("language")
        recording = request.FILES.get("audioBlob")
        recording = Recording(recording=recording, language=language)
        recording.save()
        return HttpResponse(
            json.dumps({"uuid": str(recording.uuid)}),
            status=200,
            content_type="application/json",
        )

attachment/surveys/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link href="https://vjs.zencdn.net/8.3.0/video-js.css" rel="stylesheet" />
    <link rel="stylesheet" href="//unpkg.com/videojs-wavesurfer/dist/css/videojs.wavesurfer.min.css" />
    <link rel="stylesheet" href="//unpkg.com/videojs-record/dist/css/videojs.record.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
    {% block head %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    {% load i18n %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    {% get_current_language as LANGUAGE_CODE %}
    <header>
      <nav>
        <div class="nav-wrapper">
          <ul class="left-align">
            {% for language in languages %}
              {% if language.code == 'pt' %}

              {% else %}
                <li>
                  {{ language.code }}
                  <a href="/{{ language.code }}{{ request.path|slice:'3:' }}" class="btn-flat btn-small {% if language.code == LANGUAGE_CODE %}{% endif %}">{{ language.name_local }}</a>
                </li>
              {% endif %}
            {% endfor %}
          </ul>
          <a href="" class="brand-logo center"><img src="{% static 'img/cyber-t-cor.svg' %}" alt="Cyber Master" /></a>
        </div>
      </nav>
    </header>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <footer class="page-footer">
      {% block footer %}
        <div class="container">
          <p class="center-align">Copyright 2023 UPV</p>
        </div>
      {% endblock %}
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://vjs.zencdn.net/8.3.0/video.min.js"></script>
    <script src="//unpkg.com/videojs-wavesurfer/dist/videojs.wavesurfer.min.js"></script>
    <script src="//unpkg.com/videojs-record/dist/videojs.record.min.js"></script>
    <script>
      const csrftoken = $('[name=csrfmiddlewaretoken]').val()
      if (csrftoken) {
        function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method)
        }
        $.ajaxSetup({
          beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader('X-CSRFToken', csrftoken)
            }
          }
        })
      }
    </script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

attachment/surveys/templates/survey.html
<!-- survey.html -->
{% extends 'base.html' %}

{% block title %}Survey{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/survey.css' %}">
{% endblock %}

{% block content %}
<div class="container survey-wrapper">
    {% if survey.surveytranslation_set.all %}
        {% for survey_translation in survey.surveytranslation_set.all %}
            {% if survey_translation.language == LANGUAGE_CODE %}
                <h1 class="survey-title">{{survey_translation.title}}</h1>
            {% endif %}
        {% endfor %}
    {% else %}
        <h1 class="survey-title">{{survey.name}}</h1>
    {% endif %}


    <form action="{{ request.get_full_path }}" method="post" class="container" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="language" value="{{ LANGUAGE_CODE }}">
        <input type="hidden" name="response-uuid" value="{{ uuid }}">
        <div class="row">
            {% for screen_id, questions  in survey.checked_screens.items %}
                <div class="screen-container" id="screen_{{screen_id}}">
                    <div class="input-field col s12">
                        {% for question in questions %}
                            <div class="question-container {% if question.hidden %}hide hiddable{% endif %} container {% if question.image %} centered {% endif %}" {% if question.exclusion_value %} exclusion-value={{question.exclusion_value}} {% endif%}>
                            {% if question.image %}
                                <img src="{{ question.image.url }}" alt="{{ question.image.name }}" class="survey-image">
                            {% endif %}
                            {% if question.questiontranslation_set.all %}
                                {% for question_translation in question.questiontranslation_set.all %}
                                    {% if question_translation.language == LANGUAGE_CODE %}
                                        {% with options=question_translation.options %}
                                            <p>{{ question_translation.question_prompt }}</p>
                                            {% if question.question_type == 'text' %}
                                                <input type="text" name="question_{{ question.name }}" required>
                                            {% elif question.question_type == 'prompt' %}
                                                <br>
                                            {% elif question.question_type == 'multiple_select' %}
                                                <div class="option-container {% if question.long_text %} block-label{% endif %}">
                                                    {% for option in options %}
                                                        <label {% if question.long_text %}class="block-label"{% endif %}>
                                                            <input type="checkbox" name="question_{{ question.name }}" value="{{ option.value }}">
                                                            <span>{{ option.label }}</span>
                                                            {{ option.label|length }}
                                                        </label>
                                                    {% endfor %}
                                                </div>
                                                <br>
                                            {% elif question.question_type == 'number' %}
                                                <input type="number" name="question_{{ question.name }}" required>
                                            {% elif question.question_type == 'recording' %}
                                                <div class="recording-container container">
                                                    <div class="row s12" style="width: 100%;">
                                                        <button id="startButton_{{question.name}}" class="btn waves-effect waves-light record-button startRecording col s12">Start Recording</button>
                                                        <dotlottie-player class="hide recording-animation col s12 offset-s4" src="https://lottie.host/d610f9d2-0fd5-4fe0-a7bb-af9382beb102/UgnoSoFgjn.json" background="transparent" speed="0.3" style="width: 150px; height: 150px;" loop autoplay></dotlottie-player>
                                                    </div>
                                                    <div class="row s12" style="width: 100%">
                                                        <button id="stopButton_{{question.name}}" disabled class="stopRecording col s12 hide btn waves-effect waves-light">Stop Recording</button>
                                                        <audio id="audioPlayer_{{question.name}}" controls class="audioPlayer hide col s12"></audio>
                                                    </div>
                                                    <input type="hidden" id="audioBlob_{{question.name}}" name="audio_{{question.name}}">
                                                </div>
                                            {% else %}
                                                <div class="option-container{% if question.long_text %}block-label{% endif %}">
                                                        {% for option in options %}
                                                            <label {% if question.long_text %}class="block-label"{% endif %}>
                                                                <input type="radio" name="question_{{ question.name }}" value="{{ option.value }}">
                                                                <span>{{ option.label }}</span>
                                                            </label>
                                                        {% endfor %}
                                                </div>
                                            {% endif %}
                                            <br><br>
                                        {% endwith %}
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            </div>
                        {% endfor %}
                        {% if not forloop.first %}
                        <div class="flex left">
                            <div class="input-field col s3">
                                <button class="btn waves-effect waves-light previous-button" type="button" name="action">Previous</button>
                            </div>
                        </div>
                        {% endif %}
                        {% if forloop.last %}
                        <div class="flex right">
                            <div class="input-field col s3">
                                <button class="btn waves-effect waves-light submit-button" type="submit" name="action">Submit</button>
                            </div>
                        </div>
                        {% else %}
                        <div class="flex right">
                            <div class="input-field col s3">
                                <button class="btn waves-effect waves-light next-button" type="button" name="action">Next</button>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </form>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/surveys.js' %}"></script>
    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
{% endblock %}

attachment/surveys/templates/survey_submit.html
<!-- survey_submit.html -->
{% extends 'base.html' %}
{% block content %}
    <h1>Thank you for your submission!</h1>
{% endblock %}
{% block js %}
    <script>
        {% if excluded %}
            console.log("{{ excluded }}");
        {% else %}
            {% if survey %}
                window.location.href = "{{ survey }}?uuid={{ uuid }}";
            {% endif %}
        {% endif %}
    </script>
{% endblock %}
